services:

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


  db:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    restart: always
    container_name: web
    build: .
    #    command: python manage.py runserver 0.0.0.0:8000
    #    command: gunicorn -b 0.0.0.0:8000 voditel.wsgi:application
    user: daboggg:daboggg
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 main.wsgi:application"

    env_file:
      - .env
    depends_on:
      - db
    volumes:
#      - ./:/code/
#      - ./db:/code/db/
      - static_volume:/code/static
      - media_volume:/code/media

  nginx:
    restart: always
    container_name: v_nginx
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - web
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
  db_volume:
